export const CATEGORIES = [
  'All',
  'Monsoon Essentials',
  'Electronics',
  'Books and Stationary',
  'Mobility',
  'Dorm Essentials',
  'Party Supplies',
  'Tools & Hardware',
  'Clothing & Formalwear',
  'Sports Gear',
  'Photography',
  'Gaming',
  'Music Instruments',
  'Others'
];

export const DEPARTMENTS = [
  'Agriculture',
  'Apparel & Textile Technology',
  'Architecture',
  'Biotechnology',
  'Botanical and Environmental Sciences',
  'Chemistry',
  'Civil Engineering',
  'Computational Statistics & Data Analytics',
  'Computer Engineering & Technology',
  'Computer Science',
  'Economics (Punjab School of Economics)',
  'Education',
  'Electronics Technology',
  'English',
  'Food Science & Technology',
  'Foreign Languages',
  'Guru Nanak Studies',
  'Hindi',
  'History',
  'Hotel Management & Tourism',
  'Human Genetics',
  'Laws',
  'Library & Information Science',
  'MYAS GNDU Sports Sciences and Medicine',
  'Mass Communication',
  'Mathematics',
  'Mech. Engineering',
  'Microbiology',
  'Molecular Biology & Biochemistry',
  'Pharmaceutical Sciences',
  'Physical Education',
  'Physics',
  'Physiotherapy',
  'Planning (Guru Ramdas School of Planning)',
  'Political Science',
  'Psychology',
  'Punjabi (School of Punjabi Studies)',
  'Sanskrit, Pali & Prakrit',
  'School of Social Sciences',
  'Sociology',
  'Surjit Patar Centre for Ethical AI',
  'University Business School',
  'University School of Financial Studies',
  'Urdu & Persian',
  'Visual and Performing Arts',
  'Zoology',
  'Other'
];
